name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-20.04

    steps:
    - uses: egor-tensin/setup-gcc@v1
      with:
        version: 7
    - uses: actions/checkout@v3
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make distcheck
    - name: checksum
      uses: Huy-Ngo/gha-sha@v1.1.0
      with:
        glob: libmill-*.tar.gz
    - name: publish
      uses: actions/upload-artifact@v3.1.2
      with:
        path: libmill-*.tar.gz
        if-no-files-found: error
      
