name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-20.04

    steps:
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1.3
      with:
        version: 7
    - uses: actions/checkout@v3
    - name: Run autogen.sh
      run: ./autogen.sh
    - name: Configure
      run: ./configure
    - name: Make
      run: make distcheck
    - name: Generate checksum
      uses: jmgilman/actions-generate-checksum@v1.0.0
      with:
        method: sha256
        patterns: libmill-*.tar.gz
    - name: Publish
      uses: actions/upload-artifact@v3.1.2
      with:
        path: libmill-*.tar.gz
        if-no-files-found: error
      
