name: Dev CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
  
    runs-on: ubuntu-20.04

    steps:
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1.3
      with:
        version: 7
    - uses: actions/checkout@v3
    - name: Run autogen.sh
      run: ./autogen.sh
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Test
      run: make check
      
